POST http://localhost:4009/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

###

POST http://localhost:4009/api/greet
content-type: application/json

{
	"language" : "zulu",
	"greeting" : "Sawubona"
}

###

POST https://express-api-gc1l.onrender.com/api/greet
content-type: application/json

{
	"language" : "xhosa",
	"greeting" : "Molo"
}

###

POST https://express-api-gc1l.onrender.com/api/greet
content-type: application/json

{
	"language" : "Zulu",
	"greeting" : "Sawubona"
}
